kind: pipeline
type: docker
name: multisourcefeedback

steps:
  - name: 'build and test'
    image: cypress/base
    environment:
      npm_config_loglevel: silent
      NODE_ENV: test
      DB_URL: mysql://root@mysql/test
      SENDGRID: nope
      CYPRESS_BASE_URL: http://localhost:3001
      SECRET: supersecret
    commands:
      - unset CI
      - npm ci
      - npm run build
      - npm run test:ci

  - name: push
    image: thomasjensen1194/viggobuild
    privileged: true
    volumes:
      - name: apps
        path: /apps
      - name: ssh
        path: /root/.ssh
      - name: docker_socket
        path: /var/run/docker.sock
    commands:
      - cd /apps/medmcq
      - git pull
      - docker-compose up -d --build
    when:
      event:
        - push
      branch:
        - master

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

services:
  - name: mysql
    image: mysql:5.7
    ports:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'

volumes:
  - name: apps
    host:
      path: /apps
  - name: ssh
    host:
      path: /root/.ssh
  - name: docker_socket
    host:
      path: /var/run/docker.sock
